/* generated by lia multi-emit → c */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>

static const char *_lia_typeof(long long x) { (void)x; return "number"; }
static int _lia_instanceof(long long x) { (void)x; return 0; }
static void _lia_set(long long o, const char *k) { (void)o; (void)k; }
static int _lia_isfinite(long long x) { (void)x; return 1; }
static int _lia_isnan(long long x) { (void)x; return 0; }
static long long _lia_round(long long x) { return x; }
static char *_lia_cat_c(const char *a, const char *b) {
  const char *x = a ? a : "";
  const char *y = b ? b : "";
  size_t n = strlen(x) + strlen(y) + 1;
  char *out = (char *)malloc(n);
  if (!out) return NULL;
  snprintf(out, n, "%s%s", x, y);
  return out;
}
static char *_lia_sprintf_ll(const char *fmt, long long v) {
  char *buf = (char *)malloc(64);
  if (!buf) return NULL;
  if (fmt && strstr(fmt, "kb")) snprintf(buf, 64, "%lldkb", v);
  else if (fmt && strstr(fmt, "mb")) snprintf(buf, 64, "%lldmb", v);
  else if (fmt && strstr(fmt, "gb")) snprintf(buf, 64, "%lldgb", v);
  else snprintf(buf, 64, "%lldb", v);
  return buf;
}
static const char *_lia_or_c(const char *a, const char *b) {
  if (a && a[0]) return a;
  return b ? b : "";
}

long long fib(long long n) {
  if (n <= 0) {
    return 0;
  }
  if (n == 1) {
    return 1;
  }
  return fib(n - 1) + fib(n - 2);
}
long long fast_fib(long long n) {
  long long $a = 0;
  if (n <= 0) {
    return 0;
  }
  if (n == 1) {
    return 1;
  }
  $a = 0
$b = 1
#i=2..n _lia_obj()
^b;
}
long long is_even(long long n) {
  return (n % 2 == 0);
}
