// generated by lia multi-emit → go
package main
import (
	"fmt"
)


func _lia_instanceof(x interface{}) bool { return false }
func _lia_set(_o interface{}, _k string, v interface{}) interface{} { return v }
func _lia_typeof(x interface{}) string {
	switch x.(type) {
	case nil:
		return "object"
	case bool:
		return "boolean"
	case int, int64, float64:
		return "number"
	case string:
		return "string"
	default:
		return "object"
	}
}
func _lia_at(s interface{}, i interface{}) string {
	str := _lia_str(s)
	n := _lia_num(i)
	if n < 0 || n >= int64(len(str)) { return "" }
	return str[n:n+1]
}
func _lia_code_at(s interface{}, i interface{}) int64 {
	str := _lia_str(s)
	n := _lia_num(i)
	if n < 0 || n >= int64(len(str)) { return 0 }
	return int64(str[n])
}
func _lia_isfinite(x interface{}) bool { return true }
func _lia_isnan(x interface{}) bool { return false }
func _lia_falsy(x interface{}) bool {
	if x == nil || x == false || x == int64(0) || x == 0 || x == "" { return true }
	return false
}
func _lia_len(x interface{}) int64 {
	switch v := x.(type) {
	case string:
		return int64(len(v))
	default:
		return 0
	}
}
func _lia_num(x interface{}) int64 {
	switch v := x.(type) {
	case int:
		return int64(v)
	case int64:
		return v
	case float64:
		return int64(v)
	default:
		return 0
	}
}
func _lia_obj(_ ...interface{}) interface{} { return nil }
func _lia_or(a interface{}, b interface{}) interface{} {
	if _lia_falsy(a) { return b }
	return a
}
func _lia_or_str(a string, b string) string {
	if a != "" { return a }
	return b
}
func _lia_cat(a interface{}, b interface{}) string { return _lia_str(a) + _lia_str(b) }
func _lia_str(x interface{}) string {
	switch v := x.(type) {
	case string:
		return v
	case nil:
		return ""
	case bool:
		if v {
			return "true"
		}
		return "false"
	case int:
		return _lia_itoa(v)
	case int64:
		return _lia_itoa(int(v))
	case float64:
		return _lia_itoa(int(v))
	default:
		return ""
	}
}
func _lia_abs(x interface{}) int64 {
	n := _lia_num(x)
	if n < 0 { return -n }
	return n
}
func _lia_round(x interface{}) int64 { return _lia_num(x) }
func _lia_get(_ interface{}, _ string) interface{} { return nil }
func _lia_includes(_ interface{}, _ interface{}) bool { return false }
func _lia_re_exec(_ interface{}) string { return "" }
func _lia_lower(x interface{}) string { return _lia_str(x) }
func _lia_f64(x interface{}) float64 { return float64(_lia_num(x)) }
func _lia_if(c interface{}, a interface{}, b interface{}) string {
	if _lia_falsy(c) { return _lia_str(b) }
	return _lia_str(a)
}
func _lia_itoa(n int) string {
	if n == 0 {
		return "0"
	}
	neg := n < 0
	if neg {
		n = -n
	}
	var b [32]byte
	i := len(b)
	for n > 0 {
		i--
		b[i] = byte('0' + n%10)
		n /= 10
	}
	if neg {
		i--
		b[i] = '-'
	}
	return string(b[i:])
}

func safeCompare(a int64, b int64) bool {
	var A interface{}
	_ = A
	var B interface{}
	_ = B
	var n int64
	var r int64
	var i int64
	_ = n
	_ = r
	_ = i
	A = _lia_str(a)
	B = _lia_str(b)
	n = _lia_len(A)
	r = 0
	if n!=_lia_len(B) {
		B = A
		r = 1
	}
	for i=0; _lia_num(i) < _lia_num(n); i++ {
		r = _lia_num(r) | _lia_num((_lia_code_at(A,i)^_lia_code_at(B,i)))
	}
	return _lia_num(r) == 0
}
func nativeTimingSafeEqual(a int64, b int64) bool {
	_ = a
	_ = b
	panic("LIA_EMIT_GO: JS-runtime-only (nativeTimingSafeEqual)")
}

func main() {
	if !safeCompare("ab", "ab") { panic("eq") }
	if safeCompare("a", "b") { panic("neq") }
	if safeCompare("prefix", "pre") { panic("len") }
	if !safeCompare("", "") { panic("empty") }
	fmt.Println("ok go safe-compare")
}
