/**
 * LIA → Go emitter (MVP: interface{} params, fmt.Sprint / len / byte index).
 */
import { parseLia } from './compiler.mjs';
import { parseStmts, collectAssignedIds } from './body_ast.mjs';
import { isJsRuntimeOnly, rewriteExpr } from './emit_shared.mjs';

function emitStmts(stmts, indent) {
  const pad = '\t'.repeat(indent);
  const lines = [];
  for (const st of stmts) {
    if (st.type === 'assign') {
      const rhs = rewriteExpr(st.expr, 'go');
      if (st.op === '=') lines.push(`${pad}${st.id} = ${rhs}`);
      else if (st.op === '|=') lines.push(`${pad}${st.id} |= ${rhs}`);
      else if (st.op === '+=') lines.push(`${pad}${st.id} += ${rhs}`);
      else lines.push(`${pad}${st.id} = ${st.id} ${st.op[0]} (${rhs})`);
    } else if (st.type === 'return') {
      lines.push(`${pad}return ${rewriteExpr(st.expr, 'go')}`);
    } else if (st.type === 'expr') {
      lines.push(`${pad}${rewriteExpr(st.expr, 'go')}`);
    } else if (st.type === 'if') {
      lines.push(`${pad}if ${rewriteExpr(st.cond, 'go')} {`);
      lines.push(...emitStmts(st.then, indent + 1));
      for (const e of st.elseIf || []) {
        lines.push(`${pad}} else if ${rewriteExpr(e.cond, 'go')} {`);
        lines.push(...emitStmts(e.body, indent + 1));
      }
      if (st.else) {
        lines.push(`${pad}} else {`);
        lines.push(...emitStmts(st.else, indent + 1));
      }
      lines.push(`${pad}}`);
    } else if (st.type === 'for') {
      lines.push(
        `${pad}for ${rewriteExpr(st.init, 'go')}; ${rewriteExpr(st.cond, 'go')}; ${rewriteExpr(st.step, 'go')} {`,
      );
      lines.push(...emitStmts(st.body, indent + 1));
      lines.push(`${pad}}`);
    }
  }
  return lines;
}

function goType(id) {
  // Uppercase / buf* → string; loop/accum counters → int
  if (/^[A-Z]/.test(id) || /^(ba|bb|buf)/.test(id)) return 'string';
  return 'int';
}

function goDeclLocals(locals) {
  return locals.map((id) => `\tvar ${id} ${goType(id)}`);
}

export function emitGo(liaText, opts = {}) {
  const prog = parseLia(liaText);
  const pkg = opts.package || 'main';
  const parts = [`// generated by lia multi-emit → go`, `package ${pkg}`, ``, `import "fmt"`];
  if (prog.consts) {
    parts.push(`var K = map[string]int{${Object.entries(prog.consts).map(([k, v]) => `"${k}": ${v}`).join(', ')}}`);
  }
  for (const fn of prog.fns) {
    const params = fn.params
      .split(',')
      .map((p) => p.trim())
      .filter(Boolean);
    const paramList = params.map((p) => `${p} interface{}`).join(', ');
    if (isJsRuntimeOnly(fn.body) && opts.stubRuntime !== false) {
      parts.push(
        `func ${fn.name}(${paramList}) bool {\n\tpanic("LIA_EMIT_GO: JS-runtime-only (${fn.name})")\n}`,
      );
      continue;
    }
    const stmts = parseStmts(fn.body);
    const locals = collectAssignedIds(stmts).filter((id) => !params.includes(id));
    // string vars that get String() first
    const bodyLines = [...goDeclLocals(locals), ...emitStmts(stmts, 1)];
    // fix: first assign to string locals should use := if we used var — keep var + =
    parts.push(`func ${fn.name}(${paramList}) bool {\n${bodyLines.join('\n')}\n}`);
  }
  if (opts.withMain !== false) {
    const primary = prog.exports[0] || prog.fns[0]?.name || 'safeCompare';
    parts.push(`
func main() {
	if !${primary}("ab", "ab") { panic("eq") }
	if ${primary}("a", "b") { panic("neq") }
	if ${primary}("prefix", "pre") { panic("len") }
	if !${primary}("", "") { panic("empty") }
	fmt.Println("ok go safe-compare")
}`);
  }
  return { code: parts.join('\n') + '\n', program: prog, target: 'go' };
}
