/**
 * LIA → Java emitter (peripheral; not nucleus).
 */
import { parseLia } from './compiler.mjs';
import { parseStmts, collectAssignedIds } from './body_ast.mjs';
import { isJsRuntimeOnly, rewriteExpr, emitCond, assignOpLine, isNumishId, parseParamList, emitNilDefaults, inferTypes, rewriteFnValues, isNoopExpr, safeEmitId, collectFreeHostIds, emitFreeHostDecls } from './emit_shared.mjs';
import { emitThrowLine } from './emit_rewrite.mjs';

function emitStmts(stmts, indent) {
  const pad = '    '.repeat(indent);
  const lines = [];
  for (const st of stmts) {
    if (st.type === 'assign') {
      lines.push(assignOpLine(st.id, st.op, st.expr, 'java', pad));
    } else if (st.type === 'return') {
      lines.push(`${pad}return ${rewriteExpr(st.expr, 'java')};`);
    } else if (st.type === 'throw') {
      lines.push(emitThrowLine(st.expr, 'java', pad, rewriteExpr));
    } else if (st.type === 'expr') {
      if (/^break\b/.test(st.expr.trim())) lines.push(`${pad}break;`);
      else if (/^throw\b/.test(st.expr.trim())) lines.push(emitThrowLine(st.expr, 'java', pad, rewriteExpr));
      else if (/^[A-Za-z_][\w]*$/.test(st.expr.trim())) continue;
      else if (isNoopExpr(st.expr) || isNoopExpr(rewriteExpr(st.expr, 'java'))) continue;
      else lines.push(`${pad}${rewriteExpr(st.expr, 'java')};`);
    } else if (st.type === 'if') {
      lines.push(`${pad}if (${emitCond(st.cond, 'java')}) {`);
      lines.push(...emitStmts(st.then, indent + 1));
      for (const e of st.elseIf || []) {
        lines.push(`${pad}} else if (${emitCond(e.cond, 'java')}) {`);
        lines.push(...emitStmts(e.body, indent + 1));
      }
      if (st.else) {
        lines.push(`${pad}} else {`);
        lines.push(...emitStmts(st.else, indent + 1));
      }
      lines.push(`${pad}}`);
    } else if (st.type === 'for') {
      lines.push(
        `${pad}for (${rewriteExpr(st.init, 'java')}; ${emitCond(st.cond, 'java')}; ${rewriteExpr(st.step, 'java')}) {`,
      );
      lines.push(...emitStmts(st.body, indent + 1));
      lines.push(`${pad}}`);
    } else if (st.type === 'while') {
      lines.push(`${pad}while (${emitCond(st.cond, 'java')}) {`);
      lines.push(...emitStmts(st.body, indent + 1));
      lines.push(`${pad}}`);
    }
  }
  return lines;
}

function javaType(id, inferred) {
  if (/Plural$/i.test(id) || /^is[A-Z]/.test(id)) return 'boolean';
  if (/^(value|options|ms|str|alphabet|size|defaultSize|ch|pad)$/i.test(id)) return 'Object';
  if (inferred && inferred.get(id) === 'int') return 'long';
  if (inferred && inferred.get(id) === 'bool') return 'boolean';
  if (isNumishId(id) || /^(len|n|i|idx|count|num|bytes|val|msAbs)$/i.test(id) || /Abs$/i.test(id)) return 'long';
  if (/mask|step|cutoff|index|accepted|target|offset|poolNext|poolOffset|alphabetLen/i.test(id)) return 'long';
  return 'String';
}

export function emitJava(liaText, opts = {}) {
  const prog = parseLia(liaText);
  const className = opts.className || 'LinEmit';
  const parts = [
    '/* generated by lia multi-emit → java */',
    `public class ${className} {`,
    '  static String _lia_typeof(Object x) { return x == null ? "object" : "string"; }',
    '  static boolean _lia_instanceof(Object x) { return false; }',
    '  static Object _lia_set(Object o, String k, Object v) { return v; }',
    '  static boolean _lia_isfinite(Object x) { return true; }',
    '  static boolean _lia_empty(Object s) { return s == null || String.valueOf(s).isEmpty(); }',
    '  static long _lia_abs(Object x) { try { return Math.abs(Long.parseLong(String.valueOf(x))); } catch (Exception e) { return 0L; } }',
    '  static long _lia_round(Object x) { return _lia_abs(x); }',
    '  static String _lia_str(Object x) { return String.valueOf(x); }',
    '  static String _lia_at(Object s, Object i) { String t = String.valueOf(s); int n = (int)_lia_num(i); if (n < 0 || n >= t.length()) return ""; return t.substring(n, n+1); }',
    '  static long _lia_num(Object x) { try { return Long.parseLong(String.valueOf(x)); } catch (Exception e) { return 0L; } }',
    '  static String _lia_or(Object a, Object b) { return a == null || "".equals(a) ? String.valueOf(b) : String.valueOf(a); }',
    '  static String _lia_get(Object o, String k) { return null; }',
    '  static String _lia_obj(Object... _a) { return ""; }',
    '  static boolean _lia_includes(Object s, Object x) { return String.valueOf(s).contains(String.valueOf(x)); }',
    '  static String _lia_re_exec(Object s) { return null; }',
    '  static String _lia_lower(Object x) { return String.valueOf(x).toLowerCase(); }',
    '  static boolean _lia_truthy(Object x) {',
    '    if (x == null) return false;',
    '    if (x instanceof Boolean) return (Boolean)x;',
    '    if (x instanceof String) return !((String)x).isEmpty();',
    '    if (x instanceof Number) return ((Number)x).longValue() != 0L;',
    '    return true;',
    '  }',
    '  static String[] cache = new String[64];',
    '',
  ];
  if (prog.consts) {
    for (const [k, v] of Object.entries(prog.consts)) {
      parts.push(`  static final long ${k} = ${v}L;`);
    }
  }
  const fileHosty = opts.stubRuntime !== false && prog.fns.some((f) => isJsRuntimeOnly(f.body, f.name));
  for (const fn of prog.fns) {
    const { names: params, defaults } = parseParamList(fn.params);
    if (fileHosty || (isJsRuntimeOnly(fn.body, fn.name) && opts.stubRuntime !== false)) {
      parts.push(`  public static boolean ${fn.name}() { throw new RuntimeException("JS-runtime-only"); }`);
      continue;
    }
    const stmts = parseStmts(
      rewriteFnValues(fn.body, prog.fns.map((f) => f.name).filter((n) => n !== fn.name), 'null'),
    );
    const inferred = inferTypes(stmts);
    const assigned = collectAssignedIds(stmts).filter((id) => !params.includes(id) && id !== 'cache').map(safeEmitId);
    const paramList = params.map((p) => `${javaType(p, inferred)} ${safeEmitId(p)}`).join(', ');
    const decls = assigned.map((id) => {
      const t = javaType(id, inferred);
      const init = t === 'long' ? '0' : t === 'boolean' ? 'false' : 'null';
      return `    ${t} ${id} = ${init};`;
    });
    const emitted = emitStmts(stmts, 2);
    const ret = /is_|empty|startsWith|typeof|safeCompare/i.test(fn.name) ? 'boolean' : 'Object';
    if (!/\breturn\b/.test(emitted.join('\n'))) {
      emitted.push(ret === 'boolean' ? '    return false;' : '    return null;');
    }
    const freeHost = emitFreeHostDecls(collectFreeHostIds(fn.body, params, prog.fns.map((f) => f.name)), 'java');
    const bodyLines = [...decls, ...freeHost, ...emitNilDefaults(defaults, 'java'), ...emitted];
    parts.push(`  public static ${ret} ${fn.name}(${paramList}) {\n${bodyLines.join('\n')}\n  }`);
  }
  parts.push('}');
  return { code: `${parts.join('\n')}\n`, program: prog, target: 'java' };
}
