/**
 * LIA → Java emitter (peripheral; not nucleus).
 */
import { parseLia } from './compiler.mjs';
import { parseStmts, collectAssignedIds } from './body_ast.mjs';
import { isJsRuntimeOnly, rewriteExpr, emitCond, assignOpLine, isNumishId } from './emit_shared.mjs';

function emitStmts(stmts, indent) {
  const pad = '    '.repeat(indent);
  const lines = [];
  for (const st of stmts) {
    if (st.type === 'assign') {
      lines.push(assignOpLine(st.id, st.op, st.expr, 'java', pad));
    } else if (st.type === 'return') {
      lines.push(`${pad}return ${rewriteExpr(st.expr, 'java')};`);
    } else if (st.type === 'expr') {
      if (/^break\b/.test(st.expr.trim())) lines.push(`${pad}break;`);
      else lines.push(`${pad}${rewriteExpr(st.expr, 'java')};`);
    } else if (st.type === 'if') {
      lines.push(`${pad}if (${emitCond(st.cond, 'java')}) {`);
      lines.push(...emitStmts(st.then, indent + 1));
      for (const e of st.elseIf || []) {
        lines.push(`${pad}} else if (${emitCond(e.cond, 'java')}) {`);
        lines.push(...emitStmts(e.body, indent + 1));
      }
      if (st.else) {
        lines.push(`${pad}} else {`);
        lines.push(...emitStmts(st.else, indent + 1));
      }
      lines.push(`${pad}}`);
    } else if (st.type === 'for') {
      lines.push(
        `${pad}for (${rewriteExpr(st.init, 'java')}; ${emitCond(st.cond, 'java')}; ${rewriteExpr(st.step, 'java')}) {`,
      );
      lines.push(...emitStmts(st.body, indent + 1));
      lines.push(`${pad}}`);
    } else if (st.type === 'while') {
      lines.push(`${pad}while (${emitCond(st.cond, 'java')}) {`);
      lines.push(...emitStmts(st.body, indent + 1));
      lines.push(`${pad}}`);
    }
  }
  return lines;
}

function javaType(id) {
  if (isNumishId(id) || /^(len|n|i|idx|count|num|bytes|val)$/i.test(id)) return 'long';
  return 'String';
}

export function emitJava(liaText, opts = {}) {
  const prog = parseLia(liaText);
  const className = opts.className || 'LinEmit';
  const parts = [
    '/* generated by lia multi-emit → java */',
    `public class ${className} {`,
    '  static String _lia_typeof(Object x) { return x == null ? "object" : "string"; }',
    '  static boolean _lia_isfinite(Object x) { return true; }',
    '  static boolean _lia_empty(String s) { return s == null || s.isEmpty(); }',
    '  static String[] cache = new String[64];',
    '',
  ];
  for (const fn of prog.fns) {
    const params = fn.params.split(',').map((p) => p.trim()).filter(Boolean);
    if (isJsRuntimeOnly(fn.body) && opts.stubRuntime !== false) {
      parts.push(`  public static boolean ${fn.name}() { throw new RuntimeException("JS-runtime-only"); }`);
      continue;
    }
    const stmts = parseStmts(fn.body);
    const assigned = collectAssignedIds(stmts).filter((id) => !params.includes(id) && id !== 'cache');
    const paramList = params.map((p) => `${javaType(p)} ${p}`).join(', ');
    const decls = assigned.map((id) => `    ${javaType(id)} ${id} = ${javaType(id) === 'long' ? '0' : 'null'};`);
    const bodyLines = [...decls, ...emitStmts(stmts, 2)];
    const ret = /==|!=|is_|empty|startsWith|typeof/.test(fn.name + fn.body) && !/leftPad|pad|join|trim/i.test(fn.name)
      ? 'boolean'
      : /leftPad|pad|join|trim|to_string|fmt/i.test(fn.name) ? 'String' : 'long';
    parts.push(`  public static ${ret} ${fn.name}(${paramList}) {\n${bodyLines.join('\n')}\n  }`);
  }
  parts.push('}');
  return { code: `${parts.join('\n')}\n`, program: prog, target: 'java' };
}
