/**
 * LIA → Rust emitter (MVP; ALWAYS_INSTALL rustc via ensure_toolchains).
 */
import { parseLia } from './compiler.mjs';
import { parseStmts, collectAssignedIds } from './body_ast.mjs';
import { isJsRuntimeOnly, rewriteExpr, snakeCase, splitPrefixIncCond, emitCond, assignOpLine, isNumishId, isStringishId, inferTypes } from './emit_shared.mjs';

function emitStmts(stmts, indent, types) {
  const pad = '    '.repeat(indent);
  const lines = [];
  for (const st of stmts) {
    if (st.type === 'assign') {
      lines.push(assignOpLine(st.id, st.op, st.expr, 'rust', pad, types));
    } else if (st.type === 'return') {
      lines.push(`${pad}return ${rewriteExpr(st.expr, 'rust')};`);
    } else if (st.type === 'expr') {
      if (/^break\b/.test(st.expr.trim())) lines.push(`${pad}break;`);
      else lines.push(`${pad}${rewriteExpr(st.expr, 'rust')};`);
    } else if (st.type === 'if') {
      lines.push(`${pad}if ${emitCond(st.cond, 'rust')} {`);
      lines.push(...emitStmts(st.then, indent + 1, types));
      for (const e of st.elseIf || []) {
        lines.push(`${pad}} else if ${emitCond(e.cond, 'rust')} {`);
        lines.push(...emitStmts(e.body, indent + 1, types));
      }
      if (st.else) {
        lines.push(`${pad}} else {`);
        lines.push(...emitStmts(st.else, indent + 1, types));
      }
      lines.push(`${pad}}`);
    } else if (st.type === 'for') {
      const init = st.init.match(/^([A-Za-z_][\w]*)\s*=\s*(.+)$/);
      const stepInc = st.step.match(/^([A-Za-z_][\w]*)\+\+$/);
      if (init && stepInc && /<\s*/.test(st.cond)) {
        // for i in start..end when cond is i<n
        const cm = st.cond.match(/^([A-Za-z_][\w]*)\s*<\s*(.+)$/);
        if (cm && cm[1] === init[1]) {
          lines.push(`${pad}for ${init[1]} in ${rewriteExpr(init[2], 'rust')}..${rewriteExpr(cm[2], 'rust')} {`);
          lines.push(...emitStmts(st.body, indent + 1, types));
          lines.push(`${pad}}`);
          continue;
        }
      }
      lines.push(`${pad}// LIA_EMIT_RUST: fallback C-for as loop`);
      if (init) lines.push(`${pad}let mut ${init[1]} = ${rewriteExpr(init[2], 'rust')};`);
      lines.push(`${pad}while ${rewriteExpr(st.cond, 'rust')} {`);
      lines.push(...emitStmts(st.body, indent + 1, types));
      if (stepInc) lines.push(`${pad}    ${stepInc[1]} += 1;`);
      else lines.push(`${pad}    ${rewriteExpr(st.step, 'rust')};`);
      lines.push(`${pad}}`);
    } else if (st.type === 'while') {
      const inc = splitPrefixIncCond(st.cond);
      if (inc) {
        lines.push(`${pad}loop {`);
        lines.push(`${pad}    ${inc.id} += 1;`);
        lines.push(`${pad}    if !(${inc.id} ${inc.op} ${rewriteExpr(inc.rhs, 'rust')}) { break; }`);
        lines.push(...emitStmts(st.body, indent + 1, types));
        lines.push(`${pad}}`);
      } else if (String(st.cond).trim() === 'true') {
        lines.push(`${pad}loop {`);
        lines.push(...emitStmts(st.body, indent + 1, types));
        lines.push(`${pad}}`);
      } else {
        lines.push(`${pad}while ${emitCond(st.cond, 'rust')} {`);
        lines.push(...emitStmts(st.body, indent + 1, types));
        lines.push(`${pad}}`);
      }
    }
  }
  return lines;
}

function rustType(id, inferred) {
  if (inferred && inferred.has(id)) {
    const t = inferred.get(id);
    if (t === 'string' || t === 'String') return 'String';
    if (t === 'int' || t === 'i32') return 'i32';
    if (t === 'bool') return 'bool';
    return t;
  }
  if (isNumishId(id)) return 'i32';
  if (isStringishId(id)) return 'String';
  return 'i32';
}

function rustLocals(locals, stmts) {
  const inferred = inferTypes(stmts);
  return locals.map((id) => `    let mut ${id}: ${rustType(id, inferred)};`);
}

export function emitRust(liaText, opts = {}) {
  const prog = parseLia(liaText);
  const parts = [
    '// generated by lia multi-emit → rust (MVP)',
    '#![allow(non_snake_case, unused_assignments, unused_variables, unused_parens, unused_mut, dead_code)]',
    'fn _lia_typeof<T>(_x: &T) -> &\'static str { "object" }',
    'fn _lia_isfinite<T>(_x: T) -> bool { true }',
    'fn _lia_isnan<T>(_x: T) -> bool { false }',
    'fn _lia_obj() -> String { String::new() }',
  ];
  for (const fn of prog.fns) {
    const name = snakeCase(fn.name);
    const params = fn.params
      .split(',')
      .map((p) => p.trim())
      .filter(Boolean);
    const paramList = params.map((p) => {
      if (isNumishId(p)) return `mut ${p}: i32`;
      return `mut ${p}: impl ToString`;
    }).join(', ');
    if (isJsRuntimeOnly(fn.body) && opts.stubRuntime !== false) {
      parts.push(
        `pub fn ${name}(${paramList}) -> bool {\n    panic!("LIA_EMIT_RUST: JS-runtime-only (${fn.name})");\n}`,
      );
      continue;
    }
    const bodyStmts = parseStmts(
      fn.body.replace(/\bString\(([A-Za-z_][\w]*)\)/g, '$1.to_string()'),
    );
    const forVars = new Set();
    const collectFor = (list) => {
      for (const st of list || []) {
        if (st.type === 'for') {
          const im = st.init.match(/^([A-Za-z_][\w]*)\s*=/);
          if (im) forVars.add(im[1]);
          collectFor(st.body);
        }
        if (st.type === 'if') {
          collectFor(st.then);
          for (const e of st.elseIf || []) collectFor(e.body);
          if (st.else) collectFor(st.else);
        }
      }
    };
    collectFor(bodyStmts);
    const bodyLocals = collectAssignedIds(bodyStmts).filter(
      (id) => !params.includes(id) && !forVars.has(id) && id !== 'cache',
    );
    const inferredTypes = inferTypes(bodyStmts);
    const cacheStub = /\bcache\b/.test(fn.body) ? ['    let cache: Vec<String> = vec![String::new(); 64];'] : [];
    const bodyLines = [...cacheStub, ...rustLocals(bodyLocals, bodyStmts), ...emitStmts(bodyStmts, 1, inferredTypes)];
    const retType = /==|!=|<=|>=|<|>|is_|empty|startsWith|endsWith|contains|typeof/.test(fn.name + fn.body)
      ? 'bool'
      : 'i32';
    parts.push(`pub fn ${name}(${paramList}) -> ${retType} {\n${bodyLines.join('\n')}\n}`);
  }
  if (opts.withMain !== false) {
    const primary = snakeCase(prog.exports[0] || prog.fns[0]?.name || 'safeCompare');
    parts.push(`
fn main() {
    assert!(${primary}("ab", "ab"));
    assert!(!${primary}("a", "b"));
    assert!(!${primary}("prefix", "pre"));
    assert!(${primary}("", ""));
    println!("ok rust safe-compare");
}`);
  }
  return { code: parts.join('\n') + '\n', program: prog, target: 'rust', stub: true };
}
