/**
 * LIA → Rust emitter (MVP stub-capable; skip rustc when toolchain absent).
 */
import { parseLia } from './compiler.mjs';
import { parseStmts, collectAssignedIds } from './body_ast.mjs';
import { isJsRuntimeOnly, rewriteExpr, snakeCase } from './emit_shared.mjs';

function emitStmts(stmts, indent) {
  const pad = '    '.repeat(indent);
  const lines = [];
  for (const st of stmts) {
    if (st.type === 'assign') {
      const rhs = rewriteExpr(st.expr, 'rust');
      if (st.op === '=') lines.push(`${pad}${st.id} = ${rhs};`);
      else if (st.op === '|=') lines.push(`${pad}${st.id} |= ${rhs};`);
      else if (st.op === '+=') lines.push(`${pad}${st.id} += ${rhs};`);
      else lines.push(`${pad}${st.id} = ${st.id} ${st.op[0]} (${rhs});`);
    } else if (st.type === 'return') {
      lines.push(`${pad}return ${rewriteExpr(st.expr, 'rust')};`);
    } else if (st.type === 'expr') {
      lines.push(`${pad}${rewriteExpr(st.expr, 'rust')};`);
    } else if (st.type === 'if') {
      lines.push(`${pad}if ${rewriteExpr(st.cond, 'rust')} {`);
      lines.push(...emitStmts(st.then, indent + 1));
      for (const e of st.elseIf || []) {
        lines.push(`${pad}} else if ${rewriteExpr(e.cond, 'rust')} {`);
        lines.push(...emitStmts(e.body, indent + 1));
      }
      if (st.else) {
        lines.push(`${pad}} else {`);
        lines.push(...emitStmts(st.else, indent + 1));
      }
      lines.push(`${pad}}`);
    } else if (st.type === 'for') {
      const init = st.init.match(/^([A-Za-z_][\w]*)\s*=\s*(.+)$/);
      const stepInc = st.step.match(/^([A-Za-z_][\w]*)\+\+$/);
      if (init && stepInc && /<\s*/.test(st.cond)) {
        // for i in start..end when cond is i<n
        const cm = st.cond.match(/^([A-Za-z_][\w]*)\s*<\s*(.+)$/);
        if (cm && cm[1] === init[1]) {
          lines.push(`${pad}for ${init[1]} in ${rewriteExpr(init[2], 'rust')}..${rewriteExpr(cm[2], 'rust')} {`);
          lines.push(...emitStmts(st.body, indent + 1));
          lines.push(`${pad}}`);
          continue;
        }
      }
      lines.push(`${pad}// LIA_EMIT_RUST: fallback C-for as loop`);
      if (init) lines.push(`${pad}let mut ${init[1]} = ${rewriteExpr(init[2], 'rust')};`);
      lines.push(`${pad}while ${rewriteExpr(st.cond, 'rust')} {`);
      lines.push(...emitStmts(st.body, indent + 1));
      if (stepInc) lines.push(`${pad}    ${stepInc[1]} += 1;`);
      else lines.push(`${pad}    ${rewriteExpr(st.step, 'rust')};`);
      lines.push(`${pad}}`);
    }
  }
  return lines;
}

function rustType(id) {
  if (/^[A-Z]/.test(id) || /^(ba|bb|buf)/.test(id)) return 'String';
  return 'i32';
}

function rustLocals(locals) {
  return locals.map((id) => `    let mut ${id}: ${rustType(id)};`);
}

export function emitRust(liaText, opts = {}) {
  const prog = parseLia(liaText);
  const parts = [
    '// generated by lia multi-emit → rust (MVP)',
    '#![allow(non_snake_case, unused_assignments, unused_variables)]',
  ];
  for (const fn of prog.fns) {
    const name = snakeCase(fn.name);
    const params = fn.params
      .split(',')
      .map((p) => p.trim())
      .filter(Boolean);
    const paramList = params.map((p) => `${p}: impl ToString`).join(', ');
    if (isJsRuntimeOnly(fn.body) && opts.stubRuntime !== false) {
      parts.push(
        `pub fn ${name}(${paramList}) -> bool {\n    panic!("LIA_EMIT_RUST: JS-runtime-only (${fn.name})");\n}`,
      );
      continue;
    }
    const bodyStmts = parseStmts(
      fn.body.replace(/\bString\(([A-Za-z_][\w]*)\)/g, '$1.to_string()'),
    );
    const forVars = new Set();
    const collectFor = (list) => {
      for (const st of list || []) {
        if (st.type === 'for') {
          const im = st.init.match(/^([A-Za-z_][\w]*)\s*=/);
          if (im) forVars.add(im[1]);
          collectFor(st.body);
        }
        if (st.type === 'if') {
          collectFor(st.then);
          for (const e of st.elseIf || []) collectFor(e.body);
          if (st.else) collectFor(st.else);
        }
      }
    };
    collectFor(bodyStmts);
    const bodyLocals = collectAssignedIds(bodyStmts).filter(
      (id) => !params.includes(id) && !forVars.has(id),
    );
    const bodyLines = [...rustLocals(bodyLocals), ...emitStmts(bodyStmts, 1)];
    parts.push(`pub fn ${name}(${paramList}) -> bool {\n${bodyLines.join('\n')}\n}`);
  }
  if (opts.withMain !== false) {
    const primary = snakeCase(prog.exports[0] || prog.fns[0]?.name || 'safeCompare');
    parts.push(`
fn main() {
    assert!(${primary}("ab", "ab"));
    assert!(!${primary}("a", "b"));
    assert!(!${primary}("prefix", "pre"));
    assert!(${primary}("", ""));
    println!("ok rust safe-compare");
}`);
  }
  return { code: parts.join('\n') + '\n', program: prog, target: 'rust', stub: true };
}
