/**
 * Shared helpers for LIA multi-target emitters.
 * @typedef {{type:'assign', id:string, op:string, expr:string}} AssignStmt
 * @typedef {{type:'return', expr:string}} ReturnStmt
 * @typedef {{type:'expr', expr:string}} ExprStmt
 * @typedef {{type:'if', cond:string, then:Stmt[], elseIf:{cond:string,body:Stmt[]}[], else:Stmt[]|null}} IfStmt
 * @typedef {{type:'for', init:string, cond:string, step:string, body:Stmt[]}} ForStmt
 * @typedef {AssignStmt|ReturnStmt|ExprStmt|IfStmt|ForStmt} Stmt
 */

export const TARGETS = ['js', 'ts', 'py', 'go', 'rust'];

export function snakeCase(name) {
  return String(name)
    .replace(/([a-z0-9])([A-Z])/g, '$1_$2')
    .replace(/-/g, '_')
    .toLowerCase();
}

/** Detect JS-runtime-only surface (Buffer/crypto) — stub on non-JS targets. */
export function isJsRuntimeOnly(body) {
  return /\b(Buffer|crypto|bufferAllocUnsafe|timingSafeEqual)\b/.test(body);
}

export function rewriteExpr(expr, target) {
  let s = String(expr || '');
  if (target === 'js' || target === 'ts') {
    s = s.replace(/!==/g, '!==');
    s = s.replace(/!=/g, '!==');
    s = s.replace(/(^|[^=!<>])==(?!=)/g, '$1===');
    return s;
  }
  if (target === 'py') {
    s = s.replace(/\bString\(([^)]+)\)/g, 'str($1)');
    s = s.replace(/\bNumber\(([^)]+)\)/g, 'float($1)');
    s = s.replace(/([A-Za-z_][\w]*)\.length\b/g, 'len($1)');
    s = s.replace(/([A-Za-z_][\w]*)\.charCodeAt\(([^)]+)\)/g, 'ord($1[$2])');
    s = s.replace(/\btrue\b/g, 'True').replace(/\bfalse\b/g, 'False');
    s = s.replace(/\bnull\b/g, 'None').replace(/\bundefined\b/g, 'None');
    return s;
  }
  if (target === 'go') {
    s = s.replace(/\bString\(([^)]+)\)/g, 'fmt.Sprint($1)');
    s = s.replace(/([A-Za-z_][\w]*)\.length\b/g, 'len($1)');
    s = s.replace(/([A-Za-z_][\w]*)\.charCodeAt\(([^)]+)\)/g, 'int($1[$2])');
    s = s.replace(/\btrue\b/g, 'true').replace(/\bfalse\b/g, 'false');
    s = s.replace(/\bnull\b|\bundefined\b/g, 'nil');
    return s;
  }
  if (target === 'rust') {
    s = s.replace(/\bString\(([^)]+)\)/g, '$1.to_string()');
    s = s.replace(/([A-Za-z_][\w]*)\.length\b/g, '$1.len()');
    s = s.replace(/([A-Za-z_][\w]*)\.charCodeAt\(([^)]+)\)/g, '$1.as_bytes()[$2] as i32');
    s = s.replace(/\btrue\b/g, 'true').replace(/\bfalse\b/g, 'false');
    s = s.replace(/\bnull\b|\bundefined\b/g, 'None');
    return s;
  }
  return s;
}

export function defaultOutPath(inPath, target) {
  const ext = { js: '.js', ts: '.ts', py: '.py', go: '.go', rust: '.rs' }[target] || `.${target}`;
  const base = String(inPath).replace(/\.(lia|ail)$/i, '');
  return `${base}.compiled${ext}`;
}

export function emitBanner(target) {
  return `/* generated by lia multi-emit → ${target} */`;
}
