/**
 * LIA → Python emitter.
 */
import { parseLia } from './compiler.mjs';
import { parseStmts, collectAssignedIds } from './body_ast.mjs';
import { isJsRuntimeOnly, rewriteExpr, snakeCase } from './emit_shared.mjs';

function emitStmts(stmts, indent) {
  const pad = '    '.repeat(indent);
  const lines = [];
  for (const st of stmts) {
    if (st.type === 'assign') {
      const rhs = rewriteExpr(st.expr, 'py');
      if (st.op === '=') lines.push(`${pad}${st.id} = ${rhs}`);
      else if (st.op === '|=') lines.push(`${pad}${st.id} |= ${rhs}`);
      else if (st.op === '+=') lines.push(`${pad}${st.id} += ${rhs}`);
      else if (st.op === '-=') lines.push(`${pad}${st.id} -= ${rhs}`);
      else lines.push(`${pad}${st.id} = ${st.id} ${st.op[0]} (${rhs})`);
    } else if (st.type === 'return') {
      lines.push(`${pad}return ${rewriteExpr(st.expr, 'py')}`);
    } else if (st.type === 'expr') {
      lines.push(`${pad}${rewriteExpr(st.expr, 'py')}`);
    } else if (st.type === 'if') {
      lines.push(`${pad}if ${rewriteExpr(st.cond, 'py')}:`);
      const thenL = emitStmts(st.then, indent + 1);
      lines.push(...(thenL.length ? thenL : [`${pad}    pass`]));
      for (const e of st.elseIf || []) {
        lines.push(`${pad}elif ${rewriteExpr(e.cond, 'py')}:`);
        const bl = emitStmts(e.body, indent + 1);
        lines.push(...(bl.length ? bl : [`${pad}    pass`]));
      }
      if (st.else) {
        lines.push(`${pad}else:`);
        const el = emitStmts(st.else, indent + 1);
        lines.push(...(el.length ? el : [`${pad}    pass`]));
      }
    } else if (st.type === 'for') {
      // C-style for → while
      const init = st.init.match(/^([A-Za-z_][\w]*)\s*=\s*(.+)$/);
      if (init) lines.push(`${pad}${init[1]} = ${rewriteExpr(init[2], 'py')}`);
      else lines.push(`${pad}${rewriteExpr(st.init, 'py')}`);
      lines.push(`${pad}while ${rewriteExpr(st.cond, 'py')}:`);
      const body = emitStmts(st.body, indent + 1);
      lines.push(...(body.length ? body : [`${pad}    pass`]));
      const step = st.step.match(/^([A-Za-z_][\w]*)\+\+$/);
      const step2 = st.step.match(/^([A-Za-z_][\w]*)\-\-$/);
      if (step) lines.push(`${pad}    ${step[1]} += 1`);
      else if (step2) lines.push(`${pad}    ${step2[1]} -= 1`);
      else lines.push(`${pad}    ${rewriteExpr(st.step, 'py')}`);
    }
  }
  return lines;
}

export function emitPy(liaText, opts = {}) {
  const prog = parseLia(liaText);
  const parts = ['# generated by lia multi-emit → py'];
  if (prog.consts) {
    parts.push(`K = {${Object.entries(prog.consts).map(([k, v]) => `${JSON.stringify(k)}: ${v}`).join(', ')}}`);
  }
  for (const fn of prog.fns) {
    const name = snakeCase(fn.name);
    const params = fn.params
      .split(',')
      .map((p) => p.trim())
      .filter(Boolean);
    if (isJsRuntimeOnly(fn.body) && opts.stubRuntime !== false) {
      parts.push(`def ${name}(*_args, **_kwargs):\n    raise NotImplementedError("LIA_EMIT_PY: JS-runtime-only (${fn.name})")`);
      continue;
    }
    const stmts = parseStmts(fn.body);
    const locals = collectAssignedIds(stmts).filter((id) => !params.includes(id));
    const body = [];
    // Python needs locals assigned before use; first assign handles it
    void locals;
    body.push(...emitStmts(stmts, 1));
    if (!body.length) body.push('    pass');
    parts.push(`def ${name}(${params.join(', ')}):\n${body.join('\n')}`);
  }
  const ex = (prog.exports.length ? prog.exports : prog.fns.map((f) => f.name)).map(snakeCase);
  parts.push(`\n__all__ = [${ex.map((n) => JSON.stringify(n)).join(', ')}]`);
  return { code: parts.join('\n') + '\n', program: prog, target: 'py' };
}
