/**
 * LIA → Rust emitter (MVP; ALWAYS_INSTALL rustc via ensure_toolchains).
 */
import { parseLia } from './compiler.mjs';
import { parseStmts, collectAssignedIds } from './body_ast.mjs';
import { isJsRuntimeOnly, rewriteExpr, snakeCase, splitPrefixIncCond, emitCond, assignOpLine, isNumishId, isStringishId, inferTypes, parseParamList, rewriteFnValues, safeEmitId, isNoopExpr } from './emit_shared.mjs';
import { emitThrowLine, rewriteSiblingCalls } from './emit_rewrite.mjs';

function emitStmts(stmts, indent, types, retType) {
  const pad = '    '.repeat(indent);
  const lines = [];
  for (const st of stmts) {
    if (st.type === 'assign') {
      lines.push(assignOpLine(st.id, st.op, st.expr, 'rust', pad, types));
    } else if (st.type === 'return') {
      const e = rewriteExpr(st.expr, 'rust');
      if (retType === 'String') lines.push(`${pad}return _lia_val(${e});`);
      else lines.push(`${pad}return ${e};`);
    } else if (st.type === 'throw') {
      lines.push(emitThrowLine(st.expr, 'rust', pad, rewriteExpr));
    } else if (st.type === 'expr') {
      if (/^break\b/.test(st.expr.trim())) lines.push(`${pad}break;`);
      else if (/^throw\b/.test(st.expr.trim())) lines.push(emitThrowLine(st.expr, 'rust', pad, rewriteExpr));
      else if (/^[A-Za-z_][\w]*$/.test(st.expr.trim())) continue;
      else if (isNoopExpr(st.expr) || /String::new\(\)/.test(rewriteExpr(st.expr, 'rust'))) continue;
      else lines.push(`${pad}${rewriteExpr(st.expr, 'rust')};`);
    } else if (st.type === 'if') {
      lines.push(`${pad}if ${emitCond(st.cond, 'rust')} {`);
      lines.push(...emitStmts(st.then, indent + 1, types, retType));
      for (const e of st.elseIf || []) {
        lines.push(`${pad}} else if ${emitCond(e.cond, 'rust')} {`);
        lines.push(...emitStmts(e.body, indent + 1, types, retType));
      }
      if (st.else) {
        lines.push(`${pad}} else {`);
        lines.push(...emitStmts(st.else, indent + 1, types, retType));
      }
      lines.push(`${pad}}`);
    } else if (st.type === 'for') {
      const init = st.init.match(/^([A-Za-z_][\w]*)\s*=\s*(.+)$/);
      const stepInc = st.step.match(/^([A-Za-z_][\w]*)\+\+$/);
      if (init && stepInc && /<\s*/.test(st.cond)) {
        // for i in start..end when cond is i<n
        const cm = st.cond.match(/^([A-Za-z_][\w]*)\s*<\s*(.+)$/);
        if (cm && cm[1] === init[1]) {
          lines.push(`${pad}for ${init[1]} in ${rewriteExpr(init[2], 'rust')}..${rewriteExpr(cm[2], 'rust')} {`);
          lines.push(...emitStmts(st.body, indent + 1, types, retType));
          lines.push(`${pad}}`);
          continue;
        }
      }
      lines.push(`${pad}// LIA_EMIT_RUST: fallback C-for as loop`);
      if (init) lines.push(`${pad}let mut ${init[1]} = ${rewriteExpr(init[2], 'rust')};`);
      lines.push(`${pad}while ${rewriteExpr(st.cond, 'rust')} {`);
      lines.push(...emitStmts(st.body, indent + 1, types, retType));
      if (stepInc) lines.push(`${pad}    ${stepInc[1]} += 1;`);
      else lines.push(`${pad}    ${rewriteExpr(st.step, 'rust')};`);
      lines.push(`${pad}}`);
    } else if (st.type === 'while') {
      const inc = splitPrefixIncCond(st.cond);
      if (inc) {
        lines.push(`${pad}loop {`);
        lines.push(`${pad}    ${inc.id} += 1;`);
        lines.push(`${pad}    if !(${inc.id} ${inc.op} ${rewriteExpr(inc.rhs, 'rust')}) { break; }`);
        lines.push(...emitStmts(st.body, indent + 1, types, retType));
        lines.push(`${pad}}`);
      } else if (String(st.cond).trim() === 'true') {
        lines.push(`${pad}loop {`);
        lines.push(...emitStmts(st.body, indent + 1, types, retType));
        lines.push(`${pad}}`);
      } else {
        lines.push(`${pad}while ${emitCond(st.cond, 'rust')} {`);
        lines.push(...emitStmts(st.body, indent + 1, types, retType));
        lines.push(`${pad}}`);
      }
    }
  }
  return lines;
}

function rustType(id, inferred) {
  if (inferred && inferred.has(id)) {
    const t = inferred.get(id);
    if (t === 'string' || t === 'String') return 'String';
    if (t === 'int' || t === 'i32' || t === 'i64') return 'i64';
    if (t === 'bool') return 'bool';
    return t;
  }
  if (isNumishId(id)) return 'i64';
  if (isStringishId(id)) return 'String';
  return 'String';
}

function rustLocals(locals, stmts) {
  const inferred = inferTypes(stmts);
  return locals.map((id) => {
    const sid = safeEmitId(id);
    return `    let mut ${sid}: ${rustType(sid, inferred)};`;
  });
}

export function emitRust(liaText, opts = {}) {
  const prog = parseLia(liaText);
  const parts = [
    '// generated by lia multi-emit → rust (MVP)',
    '#![allow(non_snake_case, unused_assignments, unused_variables, unused_parens, unused_mut, dead_code)]',
    'fn _lia_typeof<T>(_x: &T) -> &\'static str { "object" }',
    'fn _lia_isfinite<T>(_x: &T) -> bool { true }',
    'fn _lia_isnan<T>(_x: T) -> bool { false }',
    'fn _lia_obj() -> String { String::new() }',
    'fn _lia_abs(x: &impl ToString) -> i64 { x.to_string().parse::<i64>().unwrap_or(0).abs() }',
    'fn _lia_round(x: i64) -> i64 { x }',
    'fn _lia_str(x: impl ToString) -> String { x.to_string() }',
    'fn _lia_val(x: impl ToString) -> String { x.to_string() }',
    'fn _lia_cat<A: ToString, B: ToString>(a: &A, b: &B) -> String { format!("{}{}", a.to_string(), b.to_string()) }',
    'fn _lia_num(x: &impl ToString) -> i64 { x.to_string().parse::<i64>().unwrap_or(0) }',
    'fn _lia_at(s: &impl ToString, i: i64) -> String { let t = s.to_string(); let u = if i < 0 { 0 } else { i as usize }; t.chars().nth(u).map(|c| c.to_string()).unwrap_or_default() }',
    'fn _lia_or(a: impl ToString, b: impl ToString) -> String { let a = a.to_string(); if a.is_empty() { b.to_string() } else { a } }',
    'fn _lia_get<T>(_o: &T, _k: &str) -> String { String::new() }',
    'fn _lia_includes(s: &impl ToString, x: impl ToString) -> bool { s.to_string().contains(&x.to_string()) }',
    'fn _lia_re_exec<T>(_s: T) -> String { String::new() }',
    'fn _lia_lower(x: impl ToString) -> String { x.to_string() }',
    'fn _lia_cache_get(cache: &[String], i: i32) -> String {',
    '    let u = if i < 0 { 0 } else { i as usize };',
    '    if u < cache.len() { cache[u].clone() } else { String::new() }',
    '}',
  ];
  if (prog.consts) {
    for (const [k, v] of Object.entries(prog.consts)) parts.push(`const ${k}: i64 = ${v};`);
  }
  const aliases = Object.fromEntries(prog.fns.map((f) => [f.name, snakeCase(f.name)]));
  for (const fn of prog.fns) {
    const name = snakeCase(fn.name);
    const { names: params } = parseParamList(fn.params);
    const paramList = params.map((p) => {
      if (isNumishId(p) && !/^ms$/i.test(p)) return `mut ${p}: i64`;
      return `${p}: impl ToString`;
    }).join(', ');
    const coerce = params
      .filter((p) => !(isNumishId(p) && !/^ms$/i.test(p)))
      .map((p) => `    let mut ${p} = ${p}.to_string();`);
    if (isJsRuntimeOnly(fn.body) && opts.stubRuntime !== false) {
      parts.push(
        `pub fn ${name}(${paramList}) -> bool {\n    panic!("LIA_EMIT_RUST: JS-runtime-only (${fn.name})");\n}`,
      );
      continue;
    }
    const bodyStmts = parseStmts(
      rewriteSiblingCalls(
        rewriteFnValues(fn.body, prog.fns.map((f) => f.name).filter((n) => n !== fn.name), 'String::new()'),
        aliases,
      )
        .replace(/\bmatch\b/g, 'match_')
        .replace(/\bString\(([A-Za-z_][\w]*)\)/g, '$1.to_string()'),
    );
    const forVars = new Set();
    const collectFor = (list) => {
      for (const st of list || []) {
        if (st.type === 'for') {
          const im = st.init.match(/^([A-Za-z_][\w]*)\s*=/);
          if (im) forVars.add(im[1]);
          collectFor(st.body);
        }
        if (st.type === 'if') {
          collectFor(st.then);
          for (const e of st.elseIf || []) collectFor(e.body);
          if (st.else) collectFor(st.else);
        }
      }
    };
    collectFor(bodyStmts);
    const bodyLocals = collectAssignedIds(bodyStmts).filter(
      (id) => !params.includes(id) && !forVars.has(id) && id !== 'cache',
    );
    const inferredTypes = inferTypes(bodyStmts);
    const cacheStub = /\bcache\b/.test(fn.body)
      ? ['    let mut cache: Vec<String> = vec![String::new(); 64];']
      : [];
    const retType = /is_|empty|startsWith|endsWith|contains|typeof|^safeCompare$/i.test(fn.name)
      ? 'bool'
      : 'String';
    const emitted = emitStmts(bodyStmts, 1, inferredTypes, retType);
    if (!/\breturn\b/.test(emitted.join('\n'))) {
      emitted.push(retType === 'bool' ? '    false' : '    String::new()');
    }
    const bodyLines = [...coerce, ...cacheStub, ...rustLocals(bodyLocals, bodyStmts), ...emitted];
    parts.push(`pub fn ${name}(${paramList}) -> ${retType} {\n${bodyLines.join('\n')}\n}`);
  }
  if (opts.withMain !== false) {
    const primary = snakeCase(prog.exports[0] || prog.fns[0]?.name || 'safeCompare');
    parts.push(`
fn main() {
    assert!(${primary}("ab", "ab"));
    assert!(!${primary}("a", "b"));
    assert!(!${primary}("prefix", "pre"));
    assert!(${primary}("", ""));
    println!("ok rust safe-compare");
}`);
  }
  return { code: parts.join('\n') + '\n', program: prog, target: 'rust', stub: true };
}
