/**
 * LIA → Kotlin emitter.
 */
import { parseLia } from './compiler.mjs';
import { parseStmts, tryParseStmts, collectAssignedIds } from './body_ast.mjs';
import { isJsRuntimeOnly, rewriteExpr, emitCond, assignOpLine, isNumishId, isStringishId, isBoolishId, parseParamList, emitNilDefaults, inferTypes, isNoopExpr, safeEmitId, emitNameMap, collectFreeHostIds, emitFreeHostDecls, isBoolFnName } from './emit_shared.mjs';
import { emitThrowLine } from './emit_rewrite.mjs';
import { rawParamNames, rewriteSafeParamIds } from './emit_safe_ids_load.mjs';

function emitStmts(stmts, indent) {
  const pad = '    '.repeat(indent);
  const lines = [];
  for (const st of stmts) {
    if (st.type === 'assign') {
      lines.push(assignOpLine(st.id, st.op, st.expr, 'kotlin', pad));
    } else if (st.type === 'return') {
      lines.push(`${pad}return ${rewriteExpr(st.expr, 'kotlin')}`);
    } else if (st.type === 'throw') {
      lines.push(emitThrowLine(st.expr, 'kotlin', pad, rewriteExpr));
    } else if (st.type === 'expr') {
      if (/^break\b/.test(st.expr.trim())) lines.push(`${pad}break`);
      else if (/^throw\b/.test(st.expr.trim())) lines.push(emitThrowLine(st.expr, 'kotlin', pad, rewriteExpr));
      else if (/^[A-Za-z_][\w]*$/.test(st.expr.trim())) continue;
      else if (isNoopExpr(st.expr) || isNoopExpr(rewriteExpr(st.expr, 'kotlin'))) continue;
      else lines.push(`${pad}${rewriteExpr(st.expr, 'kotlin')}`);
    } else if (st.type === 'if') {
      lines.push(`${pad}if (${emitCond(st.cond, 'kotlin')}) {`);
      lines.push(...emitStmts(st.then, indent + 1));
      for (const e of st.elseIf || []) {
        lines.push(`${pad}} else if (${emitCond(e.cond, 'kotlin')}) {`);
        lines.push(...emitStmts(e.body, indent + 1));
      }
      if (st.else) {
        lines.push(`${pad}} else {`);
        lines.push(...emitStmts(st.else, indent + 1));
      }
      lines.push(`${pad}}`);
    } else if (st.type === 'for') {
      lines.push(`${pad}for (${rewriteExpr(st.init, 'kotlin')}; ${emitCond(st.cond, 'kotlin')}; ${rewriteExpr(st.step, 'kotlin')}) {`);
      lines.push(...emitStmts(st.body, indent + 1));
      lines.push(`${pad}}`);
    } else if (st.type === 'while') {
      lines.push(`${pad}while (${emitCond(st.cond, 'kotlin')}) {`);
      lines.push(...emitStmts(st.body, indent + 1));
      lines.push(`${pad}}`);
    }
  }
  return lines;
}

function kotlinType(id, inferred, orig) {
  const s = String(orig || id || '');
  if (/:num\b|:int\b/i.test(s)) return 'Long';
  if (/:bool\b/i.test(s)) return 'Boolean';
  if (/:string\b|:str\b/i.test(s)) return 'String';
  if (isBoolishId(id)) return 'Boolean';
  if (isNumishId(id)) return 'Long';
  if (isStringishId(id)) return 'String';
  if (inferred && inferred.get(id) === 'int') return 'Long';
  if (inferred && inferred.get(id) === 'bool') return 'Boolean';
  if (inferred && inferred.get(id) === 'string') return 'String';
  return 'Any';
}

function kotlinRetType(fn, stmts) {
  if (isBoolFnName(fn.name)) return 'Boolean';
  const inf = inferTypes(stmts);
  const rets = [];
  const walk = (list) => {
    for (const st of list || []) {
      if (st.type === 'return') { let _e = String(st.expr || '').trim(); if (_e.startsWith('(') && _e.endsWith(')')) _e = _e.slice(1, -1); rets.push(_e); }
      if (st.then) walk(st.then);
      if (st.else) walk(st.else);
      if (st.body) walk(st.body);
      for (const e of st.elseIf || []) walk(e.body);
    }
  };
  walk(stmts);
  if (!rets.length) return 'Any';
  if (rets.every((t) => /^(true|false)$/.test(t) || /(==|!=|<=|>=|<|>)/.test(t))) return 'Boolean';
  if (rets.every((t) => /^-?\d+$/.test(t) || inf.get(t) === 'int' || isNumishId(t))) return 'Long';
  if (rets.every((t) => /^["']/.test(t) || inf.get(t) === 'string' || isStringishId(t) || /_lia_cat|_lia_str/.test(t))) return 'String';
  return 'Any';
}

function kotlinDefaultInit(type) {
  if (type === 'Long') return '0L';
  if (type === 'Boolean') return 'false';
  if (type === 'String') return '""';
  return 'Any()';
}

export function emitKotlin(liaText, opts = {}) {
  const prog = parseLia(liaText);
  const parts = ['// generated by lia multi-emit → kotlin', ''];
  const fileHosty = opts.stubRuntime === true || opts.fileHosty === true;
  if (prog.consts && !fileHosty) {
    for (const [k, v] of Object.entries(prog.consts)) {
      parts.push(`val ${k}: Long = ${v}L`);
    }
  }
  const names = emitNameMap(prog.fns);
  for (const fn of prog.fns) {
    const rawNames = (fn.params || '').split(',').map(s => s.trim());
    const { names: params, defaults } = parseParamList(fn.params);
    const kName = names[fn.name];
    if (fileHosty || (isJsRuntimeOnly(fn.body, fn.name) && opts.stubRuntime !== false)) {
      parts.push(`fun ${kName}(): Boolean { throw RuntimeException("JS-runtime-only (${fn.name})") }`);
      continue;
    }
    const bodySrc = rewriteSafeParamIds(fn.body, rawParamNames(fn.params));
    const stmts = tryParseStmts(bodySrc) || tryParseStmts(rewriteSafeParamIds(fn.body, rawParamNames(fn.params)));
    if (!stmts) {
      parts.push(`fun ${kName}(): Boolean { throw RuntimeException("JS-runtime-only (${fn.name})") }`);
      continue;
    }
    const inferred = inferTypes(stmts);
    const assigned = collectAssignedIds(stmts).filter((id) => !params.includes(id));
    const paramList = params.map((p, i) => `${kotlinType(p, inferred, rawNames[i])} ${safeEmitId(p)}`).join(', ');
    const decls = assigned.map((id) => {
      const t = kotlinType(id, inferred);
      return `        var ${id}: ${t} = ${kotlinDefaultInit(t)}`;
    });
    const emitted = emitStmts(stmts, 2);
    const ret = kotlinRetType(fn, stmts);
    if (!/\breturn\b/.test(emitted.join('\n'))) {
      emitted.push(ret === 'Boolean' ? '        return false' : ret === 'Long' ? '        return 0L' : ret === 'String' ? '        return ""' : '        return Any()');
    }
    const freeHost = emitFreeHostDecls(collectFreeHostIds(fn.body, params, prog.fns.map((f) => f.name)), 'kotlin');
    const nilDefs = defaults.map(({ name, value }) => `        if (${name} == ${kotlinDefaultInit(kotlinType(name, inferred))}) ${name} = ${value}`);
    const bodyLines = [...decls, ...freeHost, ...nilDefs, ...emitted];
    parts.push(`fun ${safeEmitId(fn.name)}(${paramList}): ${ret} {\n${bodyLines.join('\n')}\n}`);
  }
  return { code: parts.join('\n') + '\n', program: prog, target: 'kotlin' };
}
