/**
 * LIA → C emitter (peripheral; not nucleus).
 */
import { parseLia } from './compiler.mjs';
import { parseStmts, tryParseStmts, collectAssignedIds } from './body_ast.mjs';
import { isJsRuntimeOnly, rewriteExpr, emitCond, assignOpLine, isNumishId, isStringishId, parseParamList, emitNilDefaults, safeEmitId, emitNameMap } from './emit_shared.mjs';
import { emitThrowLine } from './emit_rewrite.mjs';
import { rawParamNames, rewriteSafeParamIds } from './emit_safe_ids_load.mjs';
import { isQualityFnSet, formatQualityMain } from './emit_entry_main_load.mjs';

function emitStmts(stmts, indent) {
  const pad = '  '.repeat(indent);
  const lines = [];
  for (const st of stmts) {
    if (st.type === 'assign') {
      lines.push(assignOpLine(st.id, st.op, st.expr, 'c', pad));
    } else if (st.type === 'return') {
      lines.push(`${pad}return ${rewriteExpr(st.expr, 'c')};`);
    } else if (st.type === 'throw') {
      lines.push(emitThrowLine(st.expr, 'c', pad, rewriteExpr));
    } else if (st.type === 'expr') {
      if (/^break\b/.test(st.expr.trim())) lines.push(`${pad}break;`);
      else if (/^throw\b/.test(st.expr.trim())) lines.push(emitThrowLine(st.expr, 'c', pad, rewriteExpr));
      else lines.push(`${pad}${rewriteExpr(st.expr, 'c')};`);
    } else if (st.type === 'if') {
      lines.push(`${pad}if (${emitCond(st.cond, 'c')}) {`);
      lines.push(...emitStmts(st.then, indent + 1));
      for (const e of st.elseIf || []) {
        lines.push(`${pad}} else if (${emitCond(e.cond, 'c')}) {`);
        lines.push(...emitStmts(e.body, indent + 1));
      }
      if (st.else) {
        lines.push(`${pad}} else {`);
        lines.push(...emitStmts(st.else, indent + 1));
      }
      lines.push(`${pad}}`);
    } else if (st.type === 'for') {
      lines.push(
        `${pad}for (${rewriteExpr(st.init, 'c')}; ${emitCond(st.cond, 'c')}; ${rewriteExpr(st.step, 'c')}) {`,
      );
      lines.push(...emitStmts(st.body, indent + 1));
      lines.push(`${pad}}`);
    } else if (st.type === 'while') {
      lines.push(`${pad}while (${emitCond(st.cond, 'c')}) {`);
      lines.push(...emitStmts(st.body, indent + 1));
      lines.push(`${pad}}`);
    }
  }
  return lines;
}

function cTypeFor(id) {
  if (isNumishId(id)) return 'long long';
  if (isStringishId(id) || /^(str|fmt|s|key|name)/i.test(String(id || '').replace(/_+$/, ''))) return 'const char *';
  return 'long long';
}

export function emitC(liaText, opts = {}) {
  const prog = parseLia(liaText);
  const parts = [
    '/* generated by lia multi-emit → c */',
    '#include <stdio.h>',
    '#include <stdlib.h>',
    '#include <string.h>',
    '#include <stdbool.h>',
    '',
    'static const char *_lia_typeof(long long x) { (void)x; return "number"; }',
    'static int _lia_instanceof(long long x) { (void)x; return 0; }',
    'static void _lia_set(long long o, const char *k) { (void)o; (void)k; }',
    'static int _lia_isfinite(long long x) { (void)x; return 1; }',
    'static int _lia_isnan(long long x) { (void)x; return 0; }',
    'static char *_lia_cat_c(const char *a, const char *b) {',
    '  const char *x = a ? a : "";',
    '  const char *y = b ? b : "";',
    '  size_t n = strlen(x) + strlen(y) + 1;',
    '  char *out = (char *)malloc(n);',
    '  if (!out) return NULL;',
    '  snprintf(out, n, "%s%s", x, y);',
    '  return out;',
    '}',
    'static char *_lia_sprintf_ll(const char *fmt, long long v) {',
    '  char *buf = (char *)malloc(64);',
    '  if (!buf) return NULL;',
    '  if (fmt && strstr(fmt, "kb")) snprintf(buf, 64, "%lldkb", v);',
    '  else if (fmt && strstr(fmt, "mb")) snprintf(buf, 64, "%lldmb", v);',
    '  else if (fmt && strstr(fmt, "gb")) snprintf(buf, 64, "%lldgb", v);',
    '  else snprintf(buf, 64, "%lldb", v);',
    '  return buf;',
    '}',
    'static const char *_lia_or_c(const char *a, const char *b) {',
    '  if (a && a[0]) return a;',
    '  return b ? b : "";',
    '}',
    '',
  ];
  const fileHosty = opts.stubRuntime === true || opts.fileHosty === true;
  const names = emitNameMap(prog.fns);
  if (fileHosty) {
    for (const k of Object.keys(names)) names[k] = `lfn_${names[k]}`;
  }
  for (const fn of prog.fns) {
    const { names: params, defaults } = parseParamList(fn.params);
    const cName = names[fn.name];
    if (fileHosty || (isJsRuntimeOnly(fn.body, fn.name) && opts.stubRuntime !== false)) {
      parts.push(`long long ${cName}(void) { return 0; /* JS-runtime-only */ }`);
      continue;
    }
    const bodySrc = rewriteSafeParamIds(fn.body, rawParamNames(fn.params));
    const stmts = tryParseStmts(bodySrc) || tryParseStmts(fn.body);
    if (!stmts) {
      parts.push(`long long ${cName}(void) { return 0; /* JS-runtime-only */ }`);
      continue;
    }
    const assigned = collectAssignedIds(stmts);
    const paramList = params.length
      ? params.map((p) => `${cTypeFor(p)} ${safeEmitId(p)}`).join(', ')
      : 'void';
    const locals = assigned.filter((id) => !params.includes(id));
    const decls = locals.map((id) => {
      const t = cTypeFor(id);
      return `  ${t} ${id} = ${t.includes('char') ? 'NULL' : '0'};`;
    });
    const cacheStub = /\bcache\b/.test(fn.body) ? ['  const char *cache[64] = {0};'] : [];
    const bodyLines = [...cacheStub, ...decls, ...emitNilDefaults(defaults, 'c'), ...emitStmts(stmts, 1)];
    const retIsStr = /asprintf|_lia_sprintf|bytes_to_string/.test(fn.name + fn.body)
      || fn.name.includes('to_string') || fn.name.includes('ToString')
      || /leftPad|pad|join|trim/i.test(fn.name);
    const ret = retIsStr ? 'const char *' : 'long long';
    parts.push(`${ret} ${cName}(${paramList}) {\n${bodyLines.join('\n')}\n}`);
  }
  if (isQualityFnSet(prog.fns.map((f) => f.name))) {
    parts.push(formatQualityMain('c', names));
  } else if (opts.withMain === true) {
    const primary = prog.exports[0] || prog.fns[0]?.name || 'main_fn';
    parts.push(`int main(void) { printf("ok %s\\n", "${primary}"); return 0; }`);
  }
  return { code: `${parts.join('\n')}\n`, program: prog, target: 'c' };
}
