import crypto from "crypto";

export function computeSha256(data) {
  return crypto.createHash("sha256").update(data).digest("hex");
}

export class LinWorkflowEngine {
  // 1. Cálculo de Semantic Hash Hierárquico
  static computeHierarchicalHash(dag) {
    const node_hashes = {};
    const sortedNodeIds = Object.keys(dag.nodes).sort();

    for (const nid of sortedNodeIds) {
      const node = dag.nodes[nid];
      const nodePayload = JSON.stringify({
        id: node.id,
        unit: node.unit_name,
        inputs: node.inputs,
        outputs: node.outputs,
        effects: [...(node.effects || [])].sort(),
        body: node.body_ast
      });
      node_hashes[nid] = computeSha256(nodePayload);
    }

    const sortedEdges = [...dag.edges].sort((a, b) => 
      `${a.from_node}:${a.from_port}->${a.to_node}:${a.to_port}`.localeCompare(
        `${b.from_node}:${b.from_port}->${b.to_node}:${b.to_port}`
      )
    );

    const edgePayload = JSON.stringify(sortedEdges);
    const edge_hash = computeSha256(edgePayload);

    const workflowPayload = JSON.stringify({
      id: dag.id,
      entry: dag.entry_node,
      node_hashes,
      edge_hash
    });
    const workflow_hash = computeSha256(workflowPayload);

    return { node_hashes, edge_hash, workflow_hash };
  }

  // 2. Type & Effect Checker Estático nas Arestas do Grafo
  static verifyWorkflow(dag) {
    const errors = [];
    const warnings = [];
    const effect_summary = {};

    for (const edge of dag.edges) {
      const sourceNode = dag.nodes[edge.from_node];
      const targetNode = dag.nodes[edge.to_node];

      if (!sourceNode) {
        errors.push(`Edge source node '${edge.from_node}' not found in DAG.`);
        continue;
      }
      if (!targetNode) {
        errors.push(`Edge target node '${edge.to_node}' not found in DAG.`);
        continue;
      }

      const outPort = sourceNode.outputs.find(p => p.name === edge.from_port);
      const inPort = targetNode.inputs.find(p => p.name === edge.to_port);

      if (!outPort && edge.from_port !== "*") {
        errors.push(`Node '${sourceNode.id}' has no output port '${edge.from_port}'.`);
      }
      if (!inPort && edge.to_port !== "*") {
        errors.push(`Node '${targetNode.id}' has no input port '${edge.to_port}'.`);
      }
      if (outPort && inPort && outPort.type !== inPort.type && inPort.type !== "any") {
        errors.push(`Type mismatch on edge ${sourceNode.id}.${outPort.name} (${outPort.type}) -> ${targetNode.id}.${inPort.name} (${inPort.type}).`);
      }
    }

    for (const [nid, node] of Object.entries(dag.nodes)) {
      effect_summary[nid] = node.effects || [];
    }

    return {
      valid: errors.length === 0,
      errors,
      warnings,
      effect_summary
    };
  }

  // 3. Emitter Determinístico para TypeScript
  static emitTypeScript(dag) {
    const lines = [];
    lines.push(`// Generated by LIN Unified Workflow Engine -> TypeScript`);
    lines.push(`export async function run_${dag.id}(initial_input: any): Promise<any> {`);
    lines.push(`  const ctx: Record<string, any> = { initial: initial_input };`);
    
    for (const [nid, node] of Object.entries(dag.nodes)) {
      lines.push(`  // Step: ${nid} (${node.unit_name}) ~effects{${(node.effects || []).join(", ")}}`);
      if (node.control_op === "retry") {
        lines.push(`  for (let attempt = 1; attempt <= ${node.control_config?.retries || 3}; attempt++) {`);
        lines.push(`    try {`);
        lines.push(`      ctx['${nid}'] = await ${node.unit_name}(ctx);`);
        lines.push(`      break;`);
        lines.push(`    } catch (err) {`);
        lines.push(`      if (attempt === ${node.control_config?.retries || 3}) throw err;`);
        lines.push(`      await new Promise(r => setTimeout(r, Math.pow(2, attempt) * 100));`);
        lines.push(`    }`);
        lines.push(`  }`);
      } else {
        lines.push(`  ctx['${nid}'] = await ${node.unit_name}(ctx);`);
      }
    }

    lines.push(`  return ctx;`);
    lines.push(`}`);
    return lines.join("\n");
  }

  // 4. Emitter Determinístico para Rust
  static emitRust(dag) {
    const lines = [];
    lines.push(`// Generated by LIN Unified Workflow Engine -> Rust`);
    lines.push(`use std::collections::HashMap;`);
    lines.push(`pub async fn run_${dag.id}(initial_input: &str) -> Result<HashMap<String, String>, String> {`);
    lines.push(`    let mut ctx: HashMap<String, String> = HashMap::new();`);
    lines.push(`    ctx.insert("initial".to_string(), initial_input.to_string());`);
    for (const [nid, node] of Object.entries(dag.nodes)) {
      lines.push(`    // Step: ${nid} (${node.unit_name})`);
      lines.push(`    let res_${nid} = ${node.unit_name}(&ctx).await?;`);
      lines.push(`    ctx.insert("${nid}".to_string(), res_${nid});`);
    }
    lines.push(`    Ok(ctx)`);
    lines.push(`}`);
    return lines.join("\n");
  }
}
